SET NAMES 'latin1';
DROP DATABASE IF EXISTS node_crud;
CREATE DATABASE IF NOT EXISTS node_crud DEFAULT CHARACTER SET utf8;
USE node_crud;

CREATE TABLE users(
id				INTEGER NOT NULL AUTO_INCREMENT,
nombre				VARCHAR(45) NOT NULL,
PRIMARY KEY (id)
)DEFAULT CHARACTER SET utf8;

INSERT INTO users (id,nombre) VALUE (1,"Leo");
SELECT * FROM users;